name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set environment variables
      run: |
        echo "VERSION=$(sed -e s/gns3-server==//g requirements.txt)" >> $GITHUB_ENV
        echo "REPO=gns3-server" >> $GITHUB_ENV
        echo "USER=joepasss" >> $GITHUB_ENV
    
    - name: setup docker buildx
      uses: docker/setup-buildx-action@v3.10.0
      
    - name: Log in to Docker hub
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: build and push
      id: docker_build
      uses: docker/build-push-action@v6.17.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ env.USER }}/${{ env.REPO }}:${{ env.VERSION }}
          ${{ env.USER }}/${{ env.REPO }}:latest

    - name: Update Docker Hub Readme
      uses: peter-evans/dockerhub-description@v4.0.2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ env.USER }}/${{ env.REPO }}
        readme-filepath: ./README.md
